const sb=window.supabaseClient;const $=id=>document.getElementById(id);let currentPhotos=[];
function msg(t){$('loginMsg').textContent=t}function fmsg(t){$('formMsg').textContent=t}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
async function boot(){if(!sb){msg('请先配置 ../js/config.js');return}const {data:{session}}=await sb.auth.getSession();if(session)showApp();}
function showApp(){$('loginBox').style.display='none';$('app').style.display='block';$('logout').style.display='block';loadList()}
$('login').onclick=async()=>{if(!sb)return msg('请配置 Supabase');const {error}=await sb.auth.signInWithPassword({email:$('email').value,password:$('password').value});if(error)return msg(error.message);showApp()};
$('logout').onclick=async()=>{await sb.auth.signOut();location.reload()};
async function loadList(){const {data,error}=await sb.from('women').select('*').order('sort_order',{ascending:true}).order('created_at',{ascending:false});if(error){$('list').innerHTML=`<tr><td colspan="6">${esc(error.message)}</td></tr>`;return}$('list').innerHTML=(data||[]).map(w=>`<tr><td><img class="mini" src="${esc((w.photos||[])[0]||'')}" alt=""></td><td>${esc(w.name)}</td><td>${esc(w.age)}</td><td>${esc(w.city)}</td><td>${w.is_published?'已发布':'未发布'}</td><td><div class="actions"><button class="btn secondary" onclick='edit(${JSON.stringify(w).replace(/'/g,"&#39;")})'>编辑</button><button class="btn secondary" onclick="toggle('${w.id}',${!w.is_published})">${w.is_published?'下架':'发布'}</button><button class="btn danger" onclick="removeWoman('${w.id}')">删除</button></div></td></tr>`).join('')||'<tr><td colspan="6">暂无资料</td></tr>'}
$('addBtn').onclick=()=>openEditor(null);$('cancel').onclick=()=>{$('editor').style.display='none'};
function openEditor(w){$('editor').style.display='block';$('editorTitle').textContent=w?'编辑女士':'添加女士';$('id').value=w?.id||'';['name','age','city','occupation','height_cm','marital_status','short_intro','bio','hobbies','whatsapp'].forEach(k=>$(k).value=w?.[k]??'');$('is_published').checked=w?w.is_published:true;currentPhotos=w?.photos||[];renderPreview();fmsg('')}
window.edit=openEditor;
function renderPreview(){$('preview').innerHTML=currentPhotos.map((p,i)=>`<div style="position:relative"><img src="${esc(p)}" style="width:72px;height:88px;object-fit:cover"><button type="button" onclick="removePhoto(${i})" style="position:absolute;right:0;top:0">×</button></div>`).join('')}
window.removePhoto=i=>{currentPhotos.splice(i,1);renderPreview()};
$('photos').onchange=e=>{[...e.target.files].forEach(file=>{const u=URL.createObjectURL(file);currentPhotos.push(u);});renderPreview()};
async function uploadFiles(id){const files=[...$('photos').files];for(const file of files){const ext=file.name.split('.').pop().toLowerCase();const path=`${id}/${crypto.randomUUID()}.${ext}`;const {error}=await sb.storage.from('women-photos').upload(path,file,{upsert:false});if(error)throw error;const {data}=sb.storage.from('women-photos').getPublicUrl(path);currentPhotos.push(data.publicUrl)}currentPhotos=currentPhotos.filter(x=>!x.startsWith('blob:'));}
$('form').onsubmit=async e=>{e.preventDefault();fmsg('保存中…');try{let id=$('id').value||crypto.randomUUID();await uploadFiles(id);const payload={id,name:$('name').value.trim(),age:Number($('age').value),city:$('city').value.trim(),occupation:$('occupation').value.trim(),height_cm:$('height_cm').value?Number($('height_cm').value):null,marital_status:$('marital_status').value.trim(),short_intro:$('short_intro').value.trim(),bio:$('bio').value.trim(),hobbies:$('hobbies').value.trim(),whatsapp:$('whatsapp').value.replace(/\D/g,''),photos:currentPhotos,is_published:$('is_published').checked,updated_at:new Date().toISOString()};const {error}=await sb.from('women').upsert(payload);if(error)throw error;fmsg('保存成功');$('photos').value='';await loadList();setTimeout(()=>{$('editor').style.display='none'},500)}catch(err){console.error(err);fmsg('保存失败：'+err.message)}};
window.toggle=async(id,value)=>{const {error}=await sb.from('women').update({is_published:value,updated_at:new Date().toISOString()}).eq('id',id);if(error)alert(error.message);else loadList()};window.removeWoman=async id=>{if(!confirm('确定删除这位女士的资料吗？'))return;const {error}=await sb.from('women').delete().eq('id',id);if(error)alert(error.message);else loadList()};boot();
